#!/bin/bash
sudo pacman -S neovim hyprland hyprpaper hyprlock hypridle kitty waybar go php npm jdk-openjdk julia python3 python-pip python-pynvim lua51 lua-rocks ruby composer ripgrep wl-clipboard perl biber zathura xdotools zip unzip wget texlive-bin texlive-binextra fd fuzzel openssh transmission-gtk

sudo npm install -g neovim
gem install neovim

curl https://sh.rustup.rs -sSf | sh

ln -s ~/dotfiles/nvim ~/.config/nvim
ln -s ~/dotfiles/hypr ~/.config/hypr
ln -s ~/dotfiles/kitty ~/.config/kitty
ln -s ~/dotfiles/waybar ~/.config/waybar

sudo mkdir /usr/share/fonts/firacode
pushd /usr/share/fonts/firacode/
sudo wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip 
sudo unzip FiraCode.zip
popd

git config --global user.email "rubensandstrom@gmail.com"
git config --global user.name "Ruben Sandström"

